version: '3.7'
services:
  proxy:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: Proxy
      ports:
        - '8080:8080'
      restart: 'unless-stopped'
      networks:
        - backend
  server:
      build:
        context: ./node
        dockerfile: Dockerfile
      # entrypoint: wait-for database:3306 -t 15
      container_name: App
      ports:
        - '3000:3000'
      volumes:
        - ./node:/usr/src/app
      tty: true
      restart: 'unless-stopped'
      depends_on:
        - db
      networks:
        - backend
  db:
      image: mysql:5.7
      container_name: db
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql
      networks:
        - backend
volumes:
  my-db: 

networks:
  backend:
    driver: bridge
